name: test status

on:
  # push:
  #   branches:
  #     - main 
  workflow_dispatch: 

jobs:

  deploy:
    runs-on: ubuntu-latest
    permissions:
        contents: 'read'
        id-token: 'write'
    defaults:
        run: 
          shell: bash

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 

      - name: Install dependencies
        run: |
            npm install -g npm@latest 
            npm ci
      - name: Test status
        run: |
            npm test 


      - name: Run tests and collect coverage
        run: |
          nyc --reporter=lcov npm run test
        env:
          CI: true  # Ensure that NYC generates a coverage report suitable for CI

      - name: Check code coverage
        run: |
          COVERAGE_THRESHOLD=80  # Set your desired coverage threshold here
          ACTUAL_COVERAGE=$(cat coverage/lcov-report/index.html | grep -oP '(?<=<span class="strong">)[0-9]+(?=%</span>)')
          if [ "$ACTUAL_COVERAGE" -ge "$COVERAGE_THRESHOLD" ]; then
            echo "Code coverage is above $COVERAGE_THRESHOLD% - Success"
          else
            echo "Code coverage is below $COVERAGE_THRESHOLD% - Failure"
            exit 1
          fi
    